# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('reg_type', models.CharField(max_length=10)),
                ('no_of_tkt', models.IntegerField(max_length=10)),
            ],
        ),
    ]
