# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='no_of_tkt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
