# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170128_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='id_card',
            field=models.ImageField(default='', upload_to='/media'),
        ),
        migrations.AddField(
            model_name='logindata',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
