# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170129_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
